apiVersion: apps/v1
kind: Deployment
metadata:
  name: commentmanagement
  labels:
    app: commentmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commentmanagement
  template:
    metadata:
      labels:
        app: commentmanagement
    spec:
      containers:
        - name: commentmanagement
          image: "username/commentmanagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
