apiVersion: apps/v1
kind: Deployment
metadata:
  name: attachmentmanagement
  labels:
    app: attachmentmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attachmentmanagement
  template:
    metadata:
      labels:
        app: attachmentmanagement
    spec:
      containers:
        - name: attachmentmanagement
          image: "username/attachmentmanagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
