apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectmanagement
  labels:
    app: projectmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectmanagement
  template:
    metadata:
      labels:
        app: projectmanagement
    spec:
      containers:
        - name: projectmanagement
          image: "username/projectmanagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
