apiVersion: apps/v1
kind: Deployment
metadata:
  name: invitemanagement
  labels:
    app: invitemanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invitemanagement
  template:
    metadata:
      labels:
        app: invitemanagement
    spec:
      containers:
        - name: invitemanagement
          image: "username/invitemanagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
